### ISSUE TITLE
How can I get the mat files for Pulsed Phase Thermography? 

### ISSUE THREAD

**Issue by bemoregt** [neerajtiwari360/Pulse-Thermography#3]
Hi, @neerajtiwari360 

How can I get the mat files for Pulsed Phase Thermography? 

Thanks in advance.

**Comment by neerajtiwari360** [comment]
Hi, @bemoregt 
Actually I made my own Thermography System, Which you can see in .pptx file, so when ever i need the data i generate it. i have some dataset for my testing, if you want give me your mail id i will transfer it for you.

**Comment by bemoregt** [comment]
Hi, @neerajtiwari360 

My e-mail address is here:

bemore.one@gmail.com

Thanks in advance ~

**Comment by Sarieli** [comment]
Hi, @neerajtiwari360 
Do you still have dataset of mat files for Pulsed Phase Thermography.
Could you please email me some dataset.
My e-mail address is here:
ddddesperado@gmail.com
Thanks in advance.

**Comment by Sarieli** [comment]
Hi, @bemoregt 
Sorry to bother you, I am looking for mat files for Pulsed Phase Thermography and finally find you got some dataset from neerajtiwari360.
Could you please email me some dataset.
My e-mail address is here:
ddddesperado@gmail.com
Thanks in advance

**Comment by bemoregt** [comment]
I dont have dataset.

Sorry.


2018년 9월 19일 (수) 오전 10:48, sogintoNIc <notifications@github.com>님이 작성:

**Comment by bemoregt** [comment]
HI, @sogintoNIc 

Didn't you get that, Yet?

Look at this: 
https://www.edevis.com/content/en/thermography_RD.php

There is one thermogram video stream.

from @bemoregt.

**Comment by neerajtiwari360** [comment]
data_24_01_F0_2.mat
<https://drive.google.com/file/d/1gUtcs3WRu7vGXJ1RZbGS6mAQT9-6Nb1o/view?usp=drive_web>
 time_24_01_F0_2.mat
<https://drive.google.com/file/d/1Pkidv2eisk2cYQYfwT_56QQ-2cp7Tqap/view?usp=drive_web>

**Comment by Sarieli** [comment]
@bemoregt 
Thank you very much.

**Comment by Sarieli** [comment]
Hi, @neerajtiwari360 
It's very kind of you, I really appreciate for your help.
By the way, would you mind email me original pictures corresponding the mat files you gave me?
I transform dat files to images by Matlab but the effect isn't good.

**Comment by neerajtiwari360** [comment]
hello @sogintoNIc 
That Data-set is only in mat file. To apply in my algorithm I also convert the same dataset to image.

**Comment by Sarieli** [comment]
@neerajtiwari360 
Thank you for your patience and explanation, good luck to you!

**Comment by Sarieli** [comment]
Hi, @neerajtiwari360
sorry to bother you again, it's still the question concerning convert dataset to image.
My method is finding max value and min value in a 256*320 matrix then mapping the values in matrix to range of [0,1], am I right? tell me the correct method plz

**Comment by neerajtiwari360** [comment]
Hello, @sogintoNIc

Its on you where you want to use your dataset.

**Comment by watianwar** [comment]
do have matlab program for this pulse thermography detection

**Comment by watianwar** [comment]
i cannot download dataset .mat  for data from google drive. anyone have it. could you email murnihartanah123@
com
